import type { Metadata } from "next";
import "./../globals.css";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { Logo } from "@/shared/components/logo";
import { Container } from "@/shared/components/container";
import { LayoutHeader } from "./components/LayoutHeader";
import { TooltipProvider } from "@/shared/components/tooltip";
import Image from "next/image";

export const yekanBakh = localFont({
  src: "../assets/fonts/YekanBakhFaNum-VF.woff2",
  variable: "--font-yekan-bakh",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={cn("font-sans", yekanBakh.variable)}
    >
      <body
        className={`${yekanBakh.variable} ${yekanBakh.variable} antialiased bg-linear-to-b from-brand-subtle to-informal-subtle pb-10`}
      >
        <TooltipProvider>
          <LayoutHeader />

          <div className="relative z-10">{children}</div>

          <Image
            src={"/bg-pattern.png"}
            width={1920}
            height={1080}
            alt=""
            className="absolute top-0 object-cover  rotate-[5deg] scale-110 right-0 left-0 w-full"
          />
        </TooltipProvider>
      </body>
    </html>
  );
}
